// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: mark/stat.proto

package markstat

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MarksCountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarksCountRequest) Reset() {
	*x = MarksCountRequest{}
	mi := &file_mark_stat_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarksCountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarksCountRequest) ProtoMessage() {}

func (x *MarksCountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mark_stat_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarksCountRequest.ProtoReflect.Descriptor instead.
func (*MarksCountRequest) Descriptor() ([]byte, []int) {
	return file_mark_stat_proto_rawDescGZIP(), []int{0}
}

func (x *MarksCountRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type MarksCountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Count         int64                  `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarksCountResponse) Reset() {
	*x = MarksCountResponse{}
	mi := &file_mark_stat_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarksCountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarksCountResponse) ProtoMessage() {}

func (x *MarksCountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mark_stat_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarksCountResponse.ProtoReflect.Descriptor instead.
func (*MarksCountResponse) Descriptor() ([]byte, []int) {
	return file_mark_stat_proto_rawDescGZIP(), []int{1}
}

func (x *MarksCountResponse) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

var File_mark_stat_proto protoreflect.FileDescriptor

const file_mark_stat_proto_rawDesc = "" +
	"\n" +
	"\x0fmark/stat.proto\x12\bmarkstat\",\n" +
	"\x11MarksCountRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\"*\n" +
	"\x12MarksCountResponse\x12\x14\n" +
	"\x05count\x18\x01 \x01(\x03R\x05count2b\n" +
	"\x10MarkStatsService\x12N\n" +
	"\x11GetUserMarksCount\x12\x1b.markstat.MarksCountRequest\x1a\x1c.markstat.MarksCountResponseB<Z:github.com/RealTimeMap/RealTimeMap-backend/pkg/pb/markstatb\x06proto3"

var (
	file_mark_stat_proto_rawDescOnce sync.Once
	file_mark_stat_proto_rawDescData []byte
)

func file_mark_stat_proto_rawDescGZIP() []byte {
	file_mark_stat_proto_rawDescOnce.Do(func() {
		file_mark_stat_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_mark_stat_proto_rawDesc), len(file_mark_stat_proto_rawDesc)))
	})
	return file_mark_stat_proto_rawDescData
}

var file_mark_stat_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_mark_stat_proto_goTypes = []any{
	(*MarksCountRequest)(nil),  // 0: markstat.MarksCountRequest
	(*MarksCountResponse)(nil), // 1: markstat.MarksCountResponse
}
var file_mark_stat_proto_depIdxs = []int32{
	0, // 0: markstat.MarkStatsService.GetUserMarksCount:input_type -> markstat.MarksCountRequest
	1, // 1: markstat.MarkStatsService.GetUserMarksCount:output_type -> markstat.MarksCountResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_mark_stat_proto_init() }
func file_mark_stat_proto_init() {
	if File_mark_stat_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_mark_stat_proto_rawDesc), len(file_mark_stat_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_mark_stat_proto_goTypes,
		DependencyIndexes: file_mark_stat_proto_depIdxs,
		MessageInfos:      file_mark_stat_proto_msgTypes,
	}.Build()
	File_mark_stat_proto = out.File
	file_mark_stat_proto_goTypes = nil
	file_mark_stat_proto_depIdxs = nil
}
