// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: mark/stat.proto

package markstat

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MarkStatsService_GetUserMarksCount_FullMethodName           = "/markstat.MarkStatsService/GetUserMarksCount"
	MarkStatsService_GetUserMarksMonthlyActivity_FullMethodName = "/markstat.MarkStatsService/GetUserMarksMonthlyActivity"
)

// MarkStatsServiceClient is the client API for MarkStatsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MarkStatsServiceClient interface {
	GetUserMarksCount(ctx context.Context, in *MarksCountRequest, opts ...grpc.CallOption) (*MarksCountResponse, error)
	GetUserMarksMonthlyActivity(ctx context.Context, in *MarksMonthlyActivityRequest, opts ...grpc.CallOption) (*UserMarksActivityResponse, error)
}

type markStatsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMarkStatsServiceClient(cc grpc.ClientConnInterface) MarkStatsServiceClient {
	return &markStatsServiceClient{cc}
}

func (c *markStatsServiceClient) GetUserMarksCount(ctx context.Context, in *MarksCountRequest, opts ...grpc.CallOption) (*MarksCountResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MarksCountResponse)
	err := c.cc.Invoke(ctx, MarkStatsService_GetUserMarksCount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *markStatsServiceClient) GetUserMarksMonthlyActivity(ctx context.Context, in *MarksMonthlyActivityRequest, opts ...grpc.CallOption) (*UserMarksActivityResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserMarksActivityResponse)
	err := c.cc.Invoke(ctx, MarkStatsService_GetUserMarksMonthlyActivity_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MarkStatsServiceServer is the server API for MarkStatsService service.
// All implementations must embed UnimplementedMarkStatsServiceServer
// for forward compatibility.
type MarkStatsServiceServer interface {
	GetUserMarksCount(context.Context, *MarksCountRequest) (*MarksCountResponse, error)
	GetUserMarksMonthlyActivity(context.Context, *MarksMonthlyActivityRequest) (*UserMarksActivityResponse, error)
	mustEmbedUnimplementedMarkStatsServiceServer()
}

// UnimplementedMarkStatsServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMarkStatsServiceServer struct{}

func (UnimplementedMarkStatsServiceServer) GetUserMarksCount(context.Context, *MarksCountRequest) (*MarksCountResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUserMarksCount not implemented")
}
func (UnimplementedMarkStatsServiceServer) GetUserMarksMonthlyActivity(context.Context, *MarksMonthlyActivityRequest) (*UserMarksActivityResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUserMarksMonthlyActivity not implemented")
}
func (UnimplementedMarkStatsServiceServer) mustEmbedUnimplementedMarkStatsServiceServer() {}
func (UnimplementedMarkStatsServiceServer) testEmbeddedByValue()                          {}

// UnsafeMarkStatsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MarkStatsServiceServer will
// result in compilation errors.
type UnsafeMarkStatsServiceServer interface {
	mustEmbedUnimplementedMarkStatsServiceServer()
}

func RegisterMarkStatsServiceServer(s grpc.ServiceRegistrar, srv MarkStatsServiceServer) {
	// If the following call panics, it indicates UnimplementedMarkStatsServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MarkStatsService_ServiceDesc, srv)
}

func _MarkStatsService_GetUserMarksCount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MarksCountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarkStatsServiceServer).GetUserMarksCount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MarkStatsService_GetUserMarksCount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarkStatsServiceServer).GetUserMarksCount(ctx, req.(*MarksCountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MarkStatsService_GetUserMarksMonthlyActivity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MarksMonthlyActivityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarkStatsServiceServer).GetUserMarksMonthlyActivity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MarkStatsService_GetUserMarksMonthlyActivity_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarkStatsServiceServer).GetUserMarksMonthlyActivity(ctx, req.(*MarksMonthlyActivityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MarkStatsService_ServiceDesc is the grpc.ServiceDesc for MarkStatsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MarkStatsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "markstat.MarkStatsService",
	HandlerType: (*MarkStatsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetUserMarksCount",
			Handler:    _MarkStatsService_GetUserMarksCount_Handler,
		},
		{
			MethodName: "GetUserMarksMonthlyActivity",
			Handler:    _MarkStatsService_GetUserMarksMonthlyActivity_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "mark/stat.proto",
}
