// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: mark/stat.proto

package markstat

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MarksMonthlyActivityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Year          int64                  `protobuf:"varint,2,opt,name=year,proto3" json:"year,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarksMonthlyActivityRequest) Reset() {
	*x = MarksMonthlyActivityRequest{}
	mi := &file_mark_stat_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarksMonthlyActivityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarksMonthlyActivityRequest) ProtoMessage() {}

func (x *MarksMonthlyActivityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mark_stat_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarksMonthlyActivityRequest.ProtoReflect.Descriptor instead.
func (*MarksMonthlyActivityRequest) Descriptor() ([]byte, []int) {
	return file_mark_stat_proto_rawDescGZIP(), []int{0}
}

func (x *MarksMonthlyActivityRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *MarksMonthlyActivityRequest) GetYear() int64 {
	if x != nil {
		return x.Year
	}
	return 0
}

type MarkMonthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Month         string                 `protobuf:"bytes,1,opt,name=month,proto3" json:"month,omitempty"`
	Count         int64                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarkMonthResponse) Reset() {
	*x = MarkMonthResponse{}
	mi := &file_mark_stat_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkMonthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkMonthResponse) ProtoMessage() {}

func (x *MarkMonthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mark_stat_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkMonthResponse.ProtoReflect.Descriptor instead.
func (*MarkMonthResponse) Descriptor() ([]byte, []int) {
	return file_mark_stat_proto_rawDescGZIP(), []int{1}
}

func (x *MarkMonthResponse) GetMonth() string {
	if x != nil {
		return x.Month
	}
	return ""
}

func (x *MarkMonthResponse) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

type UserMarksActivityResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Activities    []*MarkMonthResponse   `protobuf:"bytes,1,rep,name=activities,proto3" json:"activities,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserMarksActivityResponse) Reset() {
	*x = UserMarksActivityResponse{}
	mi := &file_mark_stat_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserMarksActivityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserMarksActivityResponse) ProtoMessage() {}

func (x *UserMarksActivityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mark_stat_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserMarksActivityResponse.ProtoReflect.Descriptor instead.
func (*UserMarksActivityResponse) Descriptor() ([]byte, []int) {
	return file_mark_stat_proto_rawDescGZIP(), []int{2}
}

func (x *UserMarksActivityResponse) GetActivities() []*MarkMonthResponse {
	if x != nil {
		return x.Activities
	}
	return nil
}

type MarksCountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarksCountRequest) Reset() {
	*x = MarksCountRequest{}
	mi := &file_mark_stat_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarksCountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarksCountRequest) ProtoMessage() {}

func (x *MarksCountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mark_stat_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarksCountRequest.ProtoReflect.Descriptor instead.
func (*MarksCountRequest) Descriptor() ([]byte, []int) {
	return file_mark_stat_proto_rawDescGZIP(), []int{3}
}

func (x *MarksCountRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type MarksCountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Count         int64                  `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarksCountResponse) Reset() {
	*x = MarksCountResponse{}
	mi := &file_mark_stat_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarksCountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarksCountResponse) ProtoMessage() {}

func (x *MarksCountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mark_stat_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarksCountResponse.ProtoReflect.Descriptor instead.
func (*MarksCountResponse) Descriptor() ([]byte, []int) {
	return file_mark_stat_proto_rawDescGZIP(), []int{4}
}

func (x *MarksCountResponse) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

type MarksHeatMapRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	StartDate     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	EndDate       *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarksHeatMapRequest) Reset() {
	*x = MarksHeatMapRequest{}
	mi := &file_mark_stat_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarksHeatMapRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarksHeatMapRequest) ProtoMessage() {}

func (x *MarksHeatMapRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mark_stat_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarksHeatMapRequest.ProtoReflect.Descriptor instead.
func (*MarksHeatMapRequest) Descriptor() ([]byte, []int) {
	return file_mark_stat_proto_rawDescGZIP(), []int{5}
}

func (x *MarksHeatMapRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *MarksHeatMapRequest) GetStartDate() *timestamppb.Timestamp {
	if x != nil {
		return x.StartDate
	}
	return nil
}

func (x *MarksHeatMapRequest) GetEndDate() *timestamppb.Timestamp {
	if x != nil {
		return x.EndDate
	}
	return nil
}

type MarkHeatMapResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Day           *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=day,proto3" json:"day,omitempty"`
	Count         int64                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarkHeatMapResponse) Reset() {
	*x = MarkHeatMapResponse{}
	mi := &file_mark_stat_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkHeatMapResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkHeatMapResponse) ProtoMessage() {}

func (x *MarkHeatMapResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mark_stat_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkHeatMapResponse.ProtoReflect.Descriptor instead.
func (*MarkHeatMapResponse) Descriptor() ([]byte, []int) {
	return file_mark_stat_proto_rawDescGZIP(), []int{6}
}

func (x *MarkHeatMapResponse) GetDay() *timestamppb.Timestamp {
	if x != nil {
		return x.Day
	}
	return nil
}

func (x *MarkHeatMapResponse) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

type MarksHeatMapResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Activity      []*MarkHeatMapResponse `protobuf:"bytes,1,rep,name=activity,proto3" json:"activity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarksHeatMapResponse) Reset() {
	*x = MarksHeatMapResponse{}
	mi := &file_mark_stat_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarksHeatMapResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarksHeatMapResponse) ProtoMessage() {}

func (x *MarksHeatMapResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mark_stat_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarksHeatMapResponse.ProtoReflect.Descriptor instead.
func (*MarksHeatMapResponse) Descriptor() ([]byte, []int) {
	return file_mark_stat_proto_rawDescGZIP(), []int{7}
}

func (x *MarksHeatMapResponse) GetActivity() []*MarkHeatMapResponse {
	if x != nil {
		return x.Activity
	}
	return nil
}

type PopularCategoriesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TopN          int64                  `protobuf:"varint,2,opt,name=top_n,json=topN,proto3" json:"top_n,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PopularCategoriesRequest) Reset() {
	*x = PopularCategoriesRequest{}
	mi := &file_mark_stat_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PopularCategoriesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PopularCategoriesRequest) ProtoMessage() {}

func (x *PopularCategoriesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mark_stat_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PopularCategoriesRequest.ProtoReflect.Descriptor instead.
func (*PopularCategoriesRequest) Descriptor() ([]byte, []int) {
	return file_mark_stat_proto_rawDescGZIP(), []int{8}
}

func (x *PopularCategoriesRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *PopularCategoriesRequest) GetTopN() int64 {
	if x != nil {
		return x.TopN
	}
	return 0
}

type PopularCategoriesItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CategoryName  string                 `protobuf:"bytes,1,opt,name=category_name,json=categoryName,proto3" json:"category_name,omitempty"`
	Count         int64                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	Percent       float64                `protobuf:"fixed64,3,opt,name=percent,proto3" json:"percent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PopularCategoriesItem) Reset() {
	*x = PopularCategoriesItem{}
	mi := &file_mark_stat_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PopularCategoriesItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PopularCategoriesItem) ProtoMessage() {}

func (x *PopularCategoriesItem) ProtoReflect() protoreflect.Message {
	mi := &file_mark_stat_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PopularCategoriesItem.ProtoReflect.Descriptor instead.
func (*PopularCategoriesItem) Descriptor() ([]byte, []int) {
	return file_mark_stat_proto_rawDescGZIP(), []int{9}
}

func (x *PopularCategoriesItem) GetCategoryName() string {
	if x != nil {
		return x.CategoryName
	}
	return ""
}

func (x *PopularCategoriesItem) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *PopularCategoriesItem) GetPercent() float64 {
	if x != nil {
		return x.Percent
	}
	return 0
}

type PopularCategoriesResponse struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Categories    []*PopularCategoriesItem `protobuf:"bytes,1,rep,name=categories,proto3" json:"categories,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PopularCategoriesResponse) Reset() {
	*x = PopularCategoriesResponse{}
	mi := &file_mark_stat_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PopularCategoriesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PopularCategoriesResponse) ProtoMessage() {}

func (x *PopularCategoriesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mark_stat_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PopularCategoriesResponse.ProtoReflect.Descriptor instead.
func (*PopularCategoriesResponse) Descriptor() ([]byte, []int) {
	return file_mark_stat_proto_rawDescGZIP(), []int{10}
}

func (x *PopularCategoriesResponse) GetCategories() []*PopularCategoriesItem {
	if x != nil {
		return x.Categories
	}
	return nil
}

var File_mark_stat_proto protoreflect.FileDescriptor

const file_mark_stat_proto_rawDesc = "" +
	"\n" +
	"\x0fmark/stat.proto\x12\bmarkstat\x1a\x1fgoogle/protobuf/timestamp.proto\"J\n" +
	"\x1bMarksMonthlyActivityRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\x12\x12\n" +
	"\x04year\x18\x02 \x01(\x03R\x04year\"?\n" +
	"\x11MarkMonthResponse\x12\x14\n" +
	"\x05month\x18\x01 \x01(\tR\x05month\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x03R\x05count\"X\n" +
	"\x19UserMarksActivityResponse\x12;\n" +
	"\n" +
	"activities\x18\x01 \x03(\v2\x1b.markstat.MarkMonthResponseR\n" +
	"activities\",\n" +
	"\x11MarksCountRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\"*\n" +
	"\x12MarksCountResponse\x12\x14\n" +
	"\x05count\x18\x01 \x01(\x03R\x05count\"\xa0\x01\n" +
	"\x13MarksHeatMapRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\x129\n" +
	"\n" +
	"start_date\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tstartDate\x125\n" +
	"\bend_date\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\aendDate\"Y\n" +
	"\x13MarkHeatMapResponse\x12,\n" +
	"\x03day\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\x03day\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x03R\x05count\"Q\n" +
	"\x14MarksHeatMapResponse\x129\n" +
	"\bactivity\x18\x01 \x03(\v2\x1d.markstat.MarkHeatMapResponseR\bactivity\"H\n" +
	"\x18PopularCategoriesRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\x12\x13\n" +
	"\x05top_n\x18\x02 \x01(\x03R\x04topN\"l\n" +
	"\x15PopularCategoriesItem\x12#\n" +
	"\rcategory_name\x18\x01 \x01(\tR\fcategoryName\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x03R\x05count\x12\x18\n" +
	"\apercent\x18\x03 \x01(\x01R\apercent\"\\\n" +
	"\x19PopularCategoriesResponse\x12?\n" +
	"\n" +
	"categories\x18\x01 \x03(\v2\x1f.markstat.PopularCategoriesItemR\n" +
	"categories2\x88\x03\n" +
	"\x10MarkStatsService\x12N\n" +
	"\x11GetUserMarksCount\x12\x1b.markstat.MarksCountRequest\x1a\x1c.markstat.MarksCountResponse\x12i\n" +
	"\x1bGetUserMarksMonthlyActivity\x12%.markstat.MarksMonthlyActivityRequest\x1a#.markstat.UserMarksActivityResponse\x12T\n" +
	"\x13GetUserMarksHeatMap\x12\x1d.markstat.MarksHeatMapRequest\x1a\x1e.markstat.MarksHeatMapResponse\x12c\n" +
	"\x18GetPopularUserCategories\x12\".markstat.PopularCategoriesRequest\x1a#.markstat.PopularCategoriesResponseB<Z:github.com/RealTimeMap/RealTimeMap-backend/pkg/pb/markstatb\x06proto3"

var (
	file_mark_stat_proto_rawDescOnce sync.Once
	file_mark_stat_proto_rawDescData []byte
)

func file_mark_stat_proto_rawDescGZIP() []byte {
	file_mark_stat_proto_rawDescOnce.Do(func() {
		file_mark_stat_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_mark_stat_proto_rawDesc), len(file_mark_stat_proto_rawDesc)))
	})
	return file_mark_stat_proto_rawDescData
}

var file_mark_stat_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_mark_stat_proto_goTypes = []any{
	(*MarksMonthlyActivityRequest)(nil), // 0: markstat.MarksMonthlyActivityRequest
	(*MarkMonthResponse)(nil),           // 1: markstat.MarkMonthResponse
	(*UserMarksActivityResponse)(nil),   // 2: markstat.UserMarksActivityResponse
	(*MarksCountRequest)(nil),           // 3: markstat.MarksCountRequest
	(*MarksCountResponse)(nil),          // 4: markstat.MarksCountResponse
	(*MarksHeatMapRequest)(nil),         // 5: markstat.MarksHeatMapRequest
	(*MarkHeatMapResponse)(nil),         // 6: markstat.MarkHeatMapResponse
	(*MarksHeatMapResponse)(nil),        // 7: markstat.MarksHeatMapResponse
	(*PopularCategoriesRequest)(nil),    // 8: markstat.PopularCategoriesRequest
	(*PopularCategoriesItem)(nil),       // 9: markstat.PopularCategoriesItem
	(*PopularCategoriesResponse)(nil),   // 10: markstat.PopularCategoriesResponse
	(*timestamppb.Timestamp)(nil),       // 11: google.protobuf.Timestamp
}
var file_mark_stat_proto_depIdxs = []int32{
	1,  // 0: markstat.UserMarksActivityResponse.activities:type_name -> markstat.MarkMonthResponse
	11, // 1: markstat.MarksHeatMapRequest.start_date:type_name -> google.protobuf.Timestamp
	11, // 2: markstat.MarksHeatMapRequest.end_date:type_name -> google.protobuf.Timestamp
	11, // 3: markstat.MarkHeatMapResponse.day:type_name -> google.protobuf.Timestamp
	6,  // 4: markstat.MarksHeatMapResponse.activity:type_name -> markstat.MarkHeatMapResponse
	9,  // 5: markstat.PopularCategoriesResponse.categories:type_name -> markstat.PopularCategoriesItem
	3,  // 6: markstat.MarkStatsService.GetUserMarksCount:input_type -> markstat.MarksCountRequest
	0,  // 7: markstat.MarkStatsService.GetUserMarksMonthlyActivity:input_type -> markstat.MarksMonthlyActivityRequest
	5,  // 8: markstat.MarkStatsService.GetUserMarksHeatMap:input_type -> markstat.MarksHeatMapRequest
	8,  // 9: markstat.MarkStatsService.GetPopularUserCategories:input_type -> markstat.PopularCategoriesRequest
	4,  // 10: markstat.MarkStatsService.GetUserMarksCount:output_type -> markstat.MarksCountResponse
	2,  // 11: markstat.MarkStatsService.GetUserMarksMonthlyActivity:output_type -> markstat.UserMarksActivityResponse
	7,  // 12: markstat.MarkStatsService.GetUserMarksHeatMap:output_type -> markstat.MarksHeatMapResponse
	10, // 13: markstat.MarkStatsService.GetPopularUserCategories:output_type -> markstat.PopularCategoriesResponse
	10, // [10:14] is the sub-list for method output_type
	6,  // [6:10] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_mark_stat_proto_init() }
func file_mark_stat_proto_init() {
	if File_mark_stat_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_mark_stat_proto_rawDesc), len(file_mark_stat_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_mark_stat_proto_goTypes,
		DependencyIndexes: file_mark_stat_proto_depIdxs,
		MessageInfos:      file_mark_stat_proto_msgTypes,
	}.Build()
	File_mark_stat_proto = out.File
	file_mark_stat_proto_goTypes = nil
	file_mark_stat_proto_depIdxs = nil
}
