

version: "3"
services:
  loki:
    image: grafana/loki:latest
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_PASS}
    depends_on:
      - loki
    labels:
      - "traefik.enable=true"

      # grafana доступен по /grafana
      - "traefik.http.routers.grafana.rule=Host(`realtimemap.ru`) && PathPrefix(`/grafana`)"
      - "traefik.http.routers.grafana.entrypoints=websecure"
      - "traefik.http.routers.grafana.service=grafana"
      - "traefik.http.routers.grafana.tls=true"

      # Service configuration
      - "traefik.http.services.grafana.loadbalancer.server.port=3000"

    networks:
      - web


networks:
  web:
    external: true