// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: comment/comment.proto

package comment

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CommentStatsService_GetUserCommentStat_FullMethodName = "/commentservice.CommentStatsService/GetUserCommentStat"
)

// CommentStatsServiceClient is the client API for CommentStatsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CommentStatsServiceClient interface {
	GetUserCommentStat(ctx context.Context, in *CommentCountRequest, opts ...grpc.CallOption) (*CommentStatsResponse, error)
}

type commentStatsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCommentStatsServiceClient(cc grpc.ClientConnInterface) CommentStatsServiceClient {
	return &commentStatsServiceClient{cc}
}

func (c *commentStatsServiceClient) GetUserCommentStat(ctx context.Context, in *CommentCountRequest, opts ...grpc.CallOption) (*CommentStatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommentStatsResponse)
	err := c.cc.Invoke(ctx, CommentStatsService_GetUserCommentStat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CommentStatsServiceServer is the server API for CommentStatsService service.
// All implementations must embed UnimplementedCommentStatsServiceServer
// for forward compatibility.
type CommentStatsServiceServer interface {
	GetUserCommentStat(context.Context, *CommentCountRequest) (*CommentStatsResponse, error)
	mustEmbedUnimplementedCommentStatsServiceServer()
}

// UnimplementedCommentStatsServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCommentStatsServiceServer struct{}

func (UnimplementedCommentStatsServiceServer) GetUserCommentStat(context.Context, *CommentCountRequest) (*CommentStatsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUserCommentStat not implemented")
}
func (UnimplementedCommentStatsServiceServer) mustEmbedUnimplementedCommentStatsServiceServer() {}
func (UnimplementedCommentStatsServiceServer) testEmbeddedByValue()                             {}

// UnsafeCommentStatsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CommentStatsServiceServer will
// result in compilation errors.
type UnsafeCommentStatsServiceServer interface {
	mustEmbedUnimplementedCommentStatsServiceServer()
}

func RegisterCommentStatsServiceServer(s grpc.ServiceRegistrar, srv CommentStatsServiceServer) {
	// If the following call panics, it indicates UnimplementedCommentStatsServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CommentStatsService_ServiceDesc, srv)
}

func _CommentStatsService_GetUserCommentStat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommentCountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommentStatsServiceServer).GetUserCommentStat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CommentStatsService_GetUserCommentStat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommentStatsServiceServer).GetUserCommentStat(ctx, req.(*CommentCountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CommentStatsService_ServiceDesc is the grpc.ServiceDesc for CommentStatsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CommentStatsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "commentservice.CommentStatsService",
	HandlerType: (*CommentStatsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetUserCommentStat",
			Handler:    _CommentStatsService_GetUserCommentStat_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "comment/comment.proto",
}
