// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: comment/comment.proto

package comment

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CommentCountRequest struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	UserId uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// Опциональные
	StartDate     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	EndDate       *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	PrevStartDate *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=prev_start_date,json=prevStartDate,proto3" json:"prev_start_date,omitempty"`
	PrevEndDate   *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=prev_end_date,json=prevEndDate,proto3" json:"prev_end_date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommentCountRequest) Reset() {
	*x = CommentCountRequest{}
	mi := &file_comment_comment_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommentCountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommentCountRequest) ProtoMessage() {}

func (x *CommentCountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_comment_comment_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommentCountRequest.ProtoReflect.Descriptor instead.
func (*CommentCountRequest) Descriptor() ([]byte, []int) {
	return file_comment_comment_proto_rawDescGZIP(), []int{0}
}

func (x *CommentCountRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CommentCountRequest) GetStartDate() *timestamppb.Timestamp {
	if x != nil {
		return x.StartDate
	}
	return nil
}

func (x *CommentCountRequest) GetEndDate() *timestamppb.Timestamp {
	if x != nil {
		return x.EndDate
	}
	return nil
}

func (x *CommentCountRequest) GetPrevStartDate() *timestamppb.Timestamp {
	if x != nil {
		return x.PrevStartDate
	}
	return nil
}

func (x *CommentCountRequest) GetPrevEndDate() *timestamppb.Timestamp {
	if x != nil {
		return x.PrevEndDate
	}
	return nil
}

type CommentStatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Count         uint64                 `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	PrevCount     uint64                 `protobuf:"varint,2,opt,name=prev_count,json=prevCount,proto3" json:"prev_count,omitempty"`
	Direction     string                 `protobuf:"bytes,3,opt,name=direction,proto3" json:"direction,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommentStatsResponse) Reset() {
	*x = CommentStatsResponse{}
	mi := &file_comment_comment_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommentStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommentStatsResponse) ProtoMessage() {}

func (x *CommentStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_comment_comment_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommentStatsResponse.ProtoReflect.Descriptor instead.
func (*CommentStatsResponse) Descriptor() ([]byte, []int) {
	return file_comment_comment_proto_rawDescGZIP(), []int{1}
}

func (x *CommentStatsResponse) GetCount() uint64 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *CommentStatsResponse) GetPrevCount() uint64 {
	if x != nil {
		return x.PrevCount
	}
	return 0
}

func (x *CommentStatsResponse) GetDirection() string {
	if x != nil {
		return x.Direction
	}
	return ""
}

var File_comment_comment_proto protoreflect.FileDescriptor

const file_comment_comment_proto_rawDesc = "" +
	"\n" +
	"\x15comment/comment.proto\x12\x0ecommentservice\x1a\x1fgoogle/protobuf/timestamp.proto\"\xa4\x02\n" +
	"\x13CommentCountRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\x129\n" +
	"\n" +
	"start_date\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tstartDate\x125\n" +
	"\bend_date\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\aendDate\x12B\n" +
	"\x0fprev_start_date\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\rprevStartDate\x12>\n" +
	"\rprev_end_date\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\vprevEndDate\"i\n" +
	"\x14CommentStatsResponse\x12\x14\n" +
	"\x05count\x18\x01 \x01(\x04R\x05count\x12\x1d\n" +
	"\n" +
	"prev_count\x18\x02 \x01(\x04R\tprevCount\x12\x1c\n" +
	"\tdirection\x18\x03 \x01(\tR\tdirection2v\n" +
	"\x13CommentStatsService\x12_\n" +
	"\x12GetUserCommentStat\x12#.commentservice.CommentCountRequest\x1a$.commentservice.CommentStatsResponseB;Z9github.com/RealTimeMap/RealTimeMap-backend/pkg/pb/commentb\x06proto3"

var (
	file_comment_comment_proto_rawDescOnce sync.Once
	file_comment_comment_proto_rawDescData []byte
)

func file_comment_comment_proto_rawDescGZIP() []byte {
	file_comment_comment_proto_rawDescOnce.Do(func() {
		file_comment_comment_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_comment_comment_proto_rawDesc), len(file_comment_comment_proto_rawDesc)))
	})
	return file_comment_comment_proto_rawDescData
}

var file_comment_comment_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_comment_comment_proto_goTypes = []any{
	(*CommentCountRequest)(nil),   // 0: commentservice.CommentCountRequest
	(*CommentStatsResponse)(nil),  // 1: commentservice.CommentStatsResponse
	(*timestamppb.Timestamp)(nil), // 2: google.protobuf.Timestamp
}
var file_comment_comment_proto_depIdxs = []int32{
	2, // 0: commentservice.CommentCountRequest.start_date:type_name -> google.protobuf.Timestamp
	2, // 1: commentservice.CommentCountRequest.end_date:type_name -> google.protobuf.Timestamp
	2, // 2: commentservice.CommentCountRequest.prev_start_date:type_name -> google.protobuf.Timestamp
	2, // 3: commentservice.CommentCountRequest.prev_end_date:type_name -> google.protobuf.Timestamp
	0, // 4: commentservice.CommentStatsService.GetUserCommentStat:input_type -> commentservice.CommentCountRequest
	1, // 5: commentservice.CommentStatsService.GetUserCommentStat:output_type -> commentservice.CommentStatsResponse
	5, // [5:6] is the sub-list for method output_type
	4, // [4:5] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_comment_comment_proto_init() }
func file_comment_comment_proto_init() {
	if File_comment_comment_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_comment_comment_proto_rawDesc), len(file_comment_comment_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_comment_comment_proto_goTypes,
		DependencyIndexes: file_comment_comment_proto_depIdxs,
		MessageInfos:      file_comment_comment_proto_msgTypes,
	}.Build()
	File_comment_comment_proto = out.File
	file_comment_comment_proto_goTypes = nil
	file_comment_comment_proto_depIdxs = nil
}
