// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: gamification/progress.proto

package gamification

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetUserProgressRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserProgressRequest) Reset() {
	*x = GetUserProgressRequest{}
	mi := &file_gamification_progress_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserProgressRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserProgressRequest) ProtoMessage() {}

func (x *GetUserProgressRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gamification_progress_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserProgressRequest.ProtoReflect.Descriptor instead.
func (*GetUserProgressRequest) Descriptor() ([]byte, []int) {
	return file_gamification_progress_proto_rawDescGZIP(), []int{0}
}

func (x *GetUserProgressRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

// TODO Оформить более правильно в будущем
type UserProgressResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	UserId           uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CurrentLevel     uint64                 `protobuf:"varint,2,opt,name=current_level,json=currentLevel,proto3" json:"current_level,omitempty"`
	CurrentLevelName string                 `protobuf:"bytes,3,opt,name=current_level_name,json=currentLevelName,proto3" json:"current_level_name,omitempty"`
	CurrentXp        uint64                 `protobuf:"varint,4,opt,name=current_xp,json=currentXp,proto3" json:"current_xp,omitempty"`
	XpForNextLevel   uint64                 `protobuf:"varint,5,opt,name=xp_for_next_level,json=xpForNextLevel,proto3" json:"xp_for_next_level,omitempty"` // XP до некст уровня
	ProgressPercent  float64                `protobuf:"fixed64,6,opt,name=progress_percent,json=progressPercent,proto3" json:"progress_percent,omitempty"` // Процентное отображение
	NextLevel        *LevelInfo             `protobuf:"bytes,7,opt,name=next_level,json=nextLevel,proto3,oneof" json:"next_level,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *UserProgressResponse) Reset() {
	*x = UserProgressResponse{}
	mi := &file_gamification_progress_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserProgressResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserProgressResponse) ProtoMessage() {}

func (x *UserProgressResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gamification_progress_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserProgressResponse.ProtoReflect.Descriptor instead.
func (*UserProgressResponse) Descriptor() ([]byte, []int) {
	return file_gamification_progress_proto_rawDescGZIP(), []int{1}
}

func (x *UserProgressResponse) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UserProgressResponse) GetCurrentLevel() uint64 {
	if x != nil {
		return x.CurrentLevel
	}
	return 0
}

func (x *UserProgressResponse) GetCurrentLevelName() string {
	if x != nil {
		return x.CurrentLevelName
	}
	return ""
}

func (x *UserProgressResponse) GetCurrentXp() uint64 {
	if x != nil {
		return x.CurrentXp
	}
	return 0
}

func (x *UserProgressResponse) GetXpForNextLevel() uint64 {
	if x != nil {
		return x.XpForNextLevel
	}
	return 0
}

func (x *UserProgressResponse) GetProgressPercent() float64 {
	if x != nil {
		return x.ProgressPercent
	}
	return 0
}

func (x *UserProgressResponse) GetNextLevel() *LevelInfo {
	if x != nil {
		return x.NextLevel
	}
	return nil
}

type LevelInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Level         uint64                 `protobuf:"varint,1,opt,name=level,proto3" json:"level,omitempty"`
	LevelName     string                 `protobuf:"bytes,2,opt,name=level_name,json=levelName,proto3" json:"level_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LevelInfo) Reset() {
	*x = LevelInfo{}
	mi := &file_gamification_progress_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LevelInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LevelInfo) ProtoMessage() {}

func (x *LevelInfo) ProtoReflect() protoreflect.Message {
	mi := &file_gamification_progress_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LevelInfo.ProtoReflect.Descriptor instead.
func (*LevelInfo) Descriptor() ([]byte, []int) {
	return file_gamification_progress_proto_rawDescGZIP(), []int{2}
}

func (x *LevelInfo) GetLevel() uint64 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *LevelInfo) GetLevelName() string {
	if x != nil {
		return x.LevelName
	}
	return ""
}

var File_gamification_progress_proto protoreflect.FileDescriptor

const file_gamification_progress_proto_rawDesc = "" +
	"\n" +
	"\x1bgamification/progress.proto\x12\fgamification\"1\n" +
	"\x16GetUserProgressRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\"\xc3\x02\n" +
	"\x14UserProgressResponse\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\x12#\n" +
	"\rcurrent_level\x18\x02 \x01(\x04R\fcurrentLevel\x12,\n" +
	"\x12current_level_name\x18\x03 \x01(\tR\x10currentLevelName\x12\x1d\n" +
	"\n" +
	"current_xp\x18\x04 \x01(\x04R\tcurrentXp\x12)\n" +
	"\x11xp_for_next_level\x18\x05 \x01(\x04R\x0expForNextLevel\x12)\n" +
	"\x10progress_percent\x18\x06 \x01(\x01R\x0fprogressPercent\x12;\n" +
	"\n" +
	"next_level\x18\a \x01(\v2\x17.gamification.LevelInfoH\x00R\tnextLevel\x88\x01\x01B\r\n" +
	"\v_next_level\"@\n" +
	"\tLevelInfo\x12\x14\n" +
	"\x05level\x18\x01 \x01(\x04R\x05level\x12\x1d\n" +
	"\n" +
	"level_name\x18\x02 \x01(\tR\tlevelName2n\n" +
	"\x0fProgressService\x12[\n" +
	"\x0fGetUserProgress\x12$.gamification.GetUserProgressRequest\x1a\".gamification.UserProgressResponseB@Z>github.com/RealTimeMap/RealTimeMap-backend/pkg/pb/gamificationb\x06proto3"

var (
	file_gamification_progress_proto_rawDescOnce sync.Once
	file_gamification_progress_proto_rawDescData []byte
)

func file_gamification_progress_proto_rawDescGZIP() []byte {
	file_gamification_progress_proto_rawDescOnce.Do(func() {
		file_gamification_progress_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_gamification_progress_proto_rawDesc), len(file_gamification_progress_proto_rawDesc)))
	})
	return file_gamification_progress_proto_rawDescData
}

var file_gamification_progress_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_gamification_progress_proto_goTypes = []any{
	(*GetUserProgressRequest)(nil), // 0: gamification.GetUserProgressRequest
	(*UserProgressResponse)(nil),   // 1: gamification.UserProgressResponse
	(*LevelInfo)(nil),              // 2: gamification.LevelInfo
}
var file_gamification_progress_proto_depIdxs = []int32{
	2, // 0: gamification.UserProgressResponse.next_level:type_name -> gamification.LevelInfo
	0, // 1: gamification.ProgressService.GetUserProgress:input_type -> gamification.GetUserProgressRequest
	1, // 2: gamification.ProgressService.GetUserProgress:output_type -> gamification.UserProgressResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_gamification_progress_proto_init() }
func file_gamification_progress_proto_init() {
	if File_gamification_progress_proto != nil {
		return
	}
	file_gamification_progress_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gamification_progress_proto_rawDesc), len(file_gamification_progress_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_gamification_progress_proto_goTypes,
		DependencyIndexes: file_gamification_progress_proto_depIdxs,
		MessageInfos:      file_gamification_progress_proto_msgTypes,
	}.Build()
	File_gamification_progress_proto = out.File
	file_gamification_progress_proto_goTypes = nil
	file_gamification_progress_proto_depIdxs = nil
}
