env: "dev"
database:
  host: "localhost"
  port: 5432
  user: "postgres"
  password: "admin"
  db_name: "rtm_comments"
http:
  port: 8086
kafka:
  enable: false
profile:
  address: "127.0.0.1:9090"
  timeout: 3s
